services:
  - type: web
    name: audio-subtitle-pipeline
    env: python
    plan: starter
    buildCommand: pip install -r requirements-deploy.txt
    startCommand: python run.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: HF_AUTH_TOKEN
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
